### ISSUE TITLE
I'm a Manim content creator in Spanish

### ISSUE THREAD

**Issue by MathinkYT** [ManimCommunity/awesome-manim#22]
Hi! I love to make mathematical animations with Manim and I started to make videos with this Python library.

My channel's link is [here](https://www.youtube.com/channel/UCI65gVePkYfSiwj5LSOMlUw), so I would want my channel appears in the list.

That's all, thanks to all Manim creators and developers! 😄

**Comment by MathinkYT** [comment]
By the way, the source code is at [this GitHub repository](https://github.com/MathinkYT/manim_videos)

**Comment by naveen521kk** [comment]
Can you open a pull request and add yourselves to the README.md? Follow, https://awesome-manim.readthedocs.io/en/latest/contributing.html#contributing-can-be-confusing-so-here-are-a-guide.

**Comment by MathinkYT** [comment]
Of course! Thank you
