### ISSUE TITLE
 Fourier epicycles lag

### ISSUE THREAD

**Issue by mathemartics** [ManimCommunity/awesome-manim#31]
Hello, I'm  working on a new manim video with Fourier epicycles, but as you can see in [this](https://www.youtube.com/watch?v=kBbXhhFIew0) video the line that's being drawn is a bit laggy. This problem appears only when I'm working with SVG files. 
I suspect this has to do with the parametric_function_step_size and the problem is less prominent as I decrease its value, but manim crashes on my computer for values below 0.013.
Any ideas?
Thanks in advance!

**Comment by GarryBGoode** [comment]
This is the wrong place to post things like this. Please go to the discord with similar questions: [manim help discord](https://discord.gg/qbxeJuh6)

Your issue can be many things, you'll need to share the code (on discord) for us to help.

**Comment by lucasricci** [comment]
As Garry stated for Manim questions, ask them in the Manim CE discord server. I am closing this issue now.
