### ISSUE TITLE
Awesome Manim page not listing my video

### ISSUE THREAD

**Issue by negvoss** [ManimCommunity/awesome-manim#60]
Hi, I am the creator of PurpleMind (youtube.com/@PurpleMindCS) and I just posted a new video a few days ago: https://www.youtube.com/watch?v=jg6HJXVek1w&t=52s. I signed up when I created channel so that the crawler would recognize my videos and it did for the first two (after I updated the description of my video to include the word "manim") but now it seems to not be recognizing it. Would anyone be able to take a look and perhaps help identify why my content isn't being listed?

Any help is much appreciated!

Thanks.

**Comment by naveen521kk** [comment]
Looks like the recent migration to Postgres has caused some issues with the scraping process. I'll have a look at this in a few days.

**Comment by negvoss** [comment]
Okay, thank you very much!

**Comment by naveen521kk** [comment]
I've fixed the issue. I could see your video there. Let me know if anything else is broken. Thanks!

**Comment by negvoss** [comment]
Thank you!
